package com.example.vinitha.myapplication.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PROGRAM".
 */
public class Program {

    private Long id;
    private String name;
    private java.util.Date begindate;

    public Program() {
    }

    public Program(Long id) {
        this.id = id;
    }

    public Program(Long id, String name, java.util.Date begindate) {
        this.id = id;
        this.name = name;
        this.begindate = begindate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public java.util.Date getBegindate() {
        return begindate;
    }

    public void setBegindate(java.util.Date begindate) {
        this.begindate = begindate;
    }

}
